#!/bin/sh
#$1 = <dev>

# Default options to use for mounting
AUTOMOUNT_OPTS='users'
# Default type to use for mounting
AUTOMOUNT_TYPE='auto'

# Directory to look for type-specific settings
confdir=/etc/pi-usb-automount.d

# Directory to use as parent media dir for mountpoints
mediadir=/media

[ $(id -u) != 0 ] && {
    echo "This tool requires root permissions"
    exit 1
}

log() {
    echo "$*" | systemd-cat -p ${loglevel:-info} -t "pi-usb-automount"
}

acquire_lock() {
	exec 3>/var/run/media-automount.lock
	flock -x 3
}

release_lock() {
	exec 3>&-
}

alias debuglog="loglevel=debug log"
alias errorlog="loglevel=err log"

if ! [ "$1" ]
then
    errorlog "missing arguments! a device name must be provided"
    exit 1
else
    dev=/dev/${1##*/}
fi

if [ "$dev" = "$(findmnt -n -o SOURCE /)" ]
then
	log "$dev is used as rootfs, automount won't manage it"
	exit 0
fi

acquire_lock

# Check if the device exists, if not but mounted, umount it
if ! [ -b $dev ]
then
    if grep /etc/mtab -qe "^$dev"
    then
        log "$dev device removed, umounting and cleaning /media"
        if umount "$dev"
        then
            exitcode=0
        else
            exitcode=$?
            errorlog "Error umounting $dev errcode:$exitcode"
            errorlog "Command was: umount $dev"
        fi
    else
        # prevent it from failing on nonexistent devices and degrading systemctl boot
        exitcode=0
        errorlog "device doesn't exist anymore or is not a block device: $dev"
    fi

    # cleanup
    for dir in "$mediadir"/*
    do
        # Only clean non active mountpoints that have no /etc/fstab entry
        if [ -d "$dir" ] && ! mountpoint -q "$dir" && ! grep -q "^\s*[^#\s]\+\s\+${dir}" /etc/fstab; then
            rmdir "$dir"
        fi
    done
    release_lock; exit $exitcode
fi

# Load additional info for the block device
eval $(blkid -po export $dev)

# Devices with unknown type will be ignored
if [ -z "$TYPE" ]
then
    debuglog "$dev has no known filesystem type, ignoring mount request"
    release_lock; exit 0
fi

# Check /etc/fstab for an entry corresponding to the device
[ "$UUID" ] && fstab=$(grep /etc/fstab -e "^[^#]*UUID=${UUID}") || \
[ "$LABEL" ] && fstab=$(grep /etc/fstab -e "^[^#]*LABEL=${LABEL}") || \
fstab=$(grep /etc/fstab -e "^[ \t]*$dev[ \t]")

# Don't manage devices that are already in fstab
if [ "$fstab" ]
then
    debuglog "$dev already in /etc/fstab, automount won't manage it: ${fstab#\t}"
    release_lock; exit 0
fi

# directory name
prefix="${mediadir}/usb"
index=0

# Loop until an unused directory name is found
while true; do
    # Check if the index exceeds the maximum allowed value
    if [ $index -gt 99 ]; then
        echo "Error: All directory names from ${prefix}0 to ${prefix}99 are in use."
        release_lock; exit 1
    fi

    # Form the new directory name
    dir_name="${prefix}${index}"

    # Check if the directory exists
    if [ ! -d "${dir_name}" ]; then
        # If the directory does not exist, we have our name
        break
    elif [ "$(ls -A "${dir_name}" | wc -l)" -eq 0 ] && ! mountpoint -q "${dir_name}"; then
        # If the directory is empty and is not a mountpoint, we can use it
        debuglog "reusing existing empty directory ${dir_name} to mount ${dev}"
        break
    fi

    # Increment the index for the next iteration
    index=$((index + 1))
done

AUTOMOUNT_DIR="${dir_name}"

# Load Filesystem-specific configuration for mounting
if [ -e "$confdir/$TYPE" ]
then
    debuglog "loading configuration for fs type $TYPE"
    . "$confdir/$TYPE"
elif [ -e "$confdir/auto" ]
then
    . "$confdir/auto"
fi

log "mounting device $dev in $AUTOMOUNT_DIR"
mkdir -p "$AUTOMOUNT_DIR"
if mount -t "$AUTOMOUNT_TYPE" -o "$AUTOMOUNT_OPTS" "$dev" "$AUTOMOUNT_DIR"
then
    # Notify
    username="$(ps au | awk '$11 ~ /^xinit/ { print $1; exit }')"
    [ "$username" ] && DISPLAY=:0 runuser -u "$username" xdg-open "$AUTOMOUNT_DIR"
    log "Device successfully mounted: $AUTOMOUNT_DIR"
    release_lock; exit 0
else
    errorlog "Mount error: $?"
    errorlog "Command was : mount -t $AUTOMOUNT_TYPE -o $AUTOMOUNT_OPTS $dev $AUTOMOUNT_DIR"

    rmdir "$AUTOMOUNT_DIR"
    release_lock; exit 1
fi
