#!/bin/sh

set -e

case "$1" in
    remove|purge)
        # Reload udev rules and trigger them
        udevadm control --reload-rules
        udevadm trigger
        ;;
    upgrade|failed-upgrade|abort-install|abort-upgrade)
        # Handle other cases if necessary
        ;;
esac

exit 0
