#!/bin/sh
set -e

#DEBHELPER#

case "$1" in
    configure)
        udevadm control --reload-rules
        udevadm trigger
        ;;
    abort-upgrade|abort-remove|abort-deconfigure)
        ;;
    *)
        ;;
esac

exit 0
